"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2500

[character]
error_symbol = '[✗](bold red)'

[aws]
disabled = true

[package]
disabled = true

[gcloud]
disabled = true

[java]
format = '\([${symbol}(${version})]($style)\) '
style =	'bold blue'

[nodejs]
format = '\([$symbol($version)]($style)\) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
