#!/bin/sh
source "${HOME}/.zsh/zgen/zgen.zsh"

if ! zgen saved; then
  echo "Creating a zgen save"

	zgen oh-my-zsh

  # plugins
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/mvn
  zgen oh-my-zsh plugins/gradle
  zgen oh-my-zsh plugins/brew
  zgen oh-my-zsh plugins/brew-cask
  zgen oh-my-zsh plugins/osx
  zgen oh-my-zsh plugins/command-not-found
  zgen load zsh-users/zsh-syntax-highlighting
	zgen load zsh-users/zsh-history-substring-search

  # completion-only repositories. Add optional path argument to specify
  # what subdirectory of the repository to add to your fpath.
  zgen completions zsh-users/zsh-completions src

  # theme
  zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train

  # save all to init script
  zgen save
fi