#!/bin/sh
source "${HOME}/.zsh/zgen/zgen.zsh"

if ! zgen saved; then
  echo "Creating a zgen save"

	zgen oh-my-zsh

  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/mvn
  zgen oh-my-zsh plugins/gradle
  zgen oh-my-zsh plugins/brew
  zgen oh-my-zsh plugins/brew-cask
  zgen oh-my-zsh plugins/osx
  zgen oh-my-zsh plugins/command-not-found
  zgen load zsh-users/zsh-syntax-highlighting
	zgen load zsh-users/zsh-history-substring-search
	zgen load mafredri/zsh-async

  zgen load zsh-users/zsh-completions src
	
	zgen load sindresorhus/pure

  # save all to init script
  zgen save
fi